site_name: In the Basement
site_description: Comparative analysis of multiple versions of the Basement Tapes
site_url: https://mdic.github.io/inthebasement/

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - toc.follow
  palette:
    scheme: preferences
    primary: green
    accent: red

plugins:
  - search
  - autorefs
  - awesome-nav:
      files:
        - docs/songs/_songs_nav.yml

markdown_extensions:
  - attr_list

nav:
  - Home: index.md
  - About: about.md
  - Albums:
      - albums/hhbst.md
      - albums/cbst.md
      - albums/tcp.md

  - Versions:
      - versions/v01.md
  # - Songs: !include docs/songs/_songs_nav.yml
